FileExercise/ViewModels/CustomFileViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FileExercise.ViewModels
{
    public class CustomFileViewModel
    {
        public IFormFile File { get; set; }
        public string Other { get; set; }
    }
}

FileExercise/Controllers/DisplayController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace FileExercise.Controllers
{
    public class DisplayController:Controller
    {
        private readonly IHostEnvironment _env;

        public DisplayController(IHostEnvironment env)
        {
            _env = env;
        }

        public IActionResult Index()
        {
            //在发布后，这里是获取不到FileExercise根目录的，而是获取publish文件夹
            var rootPath = _env.ContentRootPath;
            var files = Directory.GetFiles(rootPath);
            
            return Ok(files.Where(o => o.EndsWith("html") | o.EndsWith("png")));
        }
    }
}

FileExercise/Controllers/DownloadController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using System.Drawing;
using System.IO;

namespace FileExercise.Controllers
{
    public class DownloadController: Controller
    {
        private readonly IHostEnvironment _env;

        private readonly string _dir;

        public DownloadController(IHostEnvironment env)
        {
            _env = env;
            _dir = _env.ContentRootPath;
        }

        /// <summary>
        /// 读取文件
        /// </summary>
        /// <returns></returns>
        public IActionResult DisplayText(string filename)
        {
            var pathname = Path.Combine(_dir, filename);
            var result = System.IO.File.ReadAllText(pathname);
            return Ok(result);
        }

        /// <summary>
        /// 返回图片
        /// </summary>
        /// <param name="filename"></param>
        /// <returns></returns>
        public IActionResult DisplayImage(string filename)
        {
            var pathname = Path.Combine(_dir, filename);
            var result64 = System.IO.File.OpenRead(pathname);

            //可以返回Base64的字符串
            //var result = Convert.ToBase64String(result64);
            //return Ok(result);

            //返回图片文件的bytes
            //return File(result64, "image/png");

            //直接返回图片文件
            //return PhysicalFile(pathname, "text/plain");
            return File(result64, "text/plain", "a.txt");
        }

        /// <summary>
        /// 可以改变图片的尺寸
        /// </summary>
        /// <param name="width"></param>
        /// <param name="filename"></param>
        /// <returns></returns>
        public IActionResult DisplayImage2(int width, string filename)
        {
            var pathname = Path.Combine(_dir, filename);
            using (var imgBmp = new Bitmap(pathname))
            {
                //找到新尺寸
                var oWidth = imgBmp.Width;
                var oHeight = imgBmp.Height;
                var height = oHeight;
                if (width > oWidth)
                {
                    width = oWidth;
                }
                else
                {
                    height = width * oHeight / oWidth;
                }
                var newImg = new Bitmap(imgBmp, width, height);
                newImg.SetResolution(72, 72);
                var ms = new MemoryStream();
                newImg.Save(ms, System.Drawing.Imaging.ImageFormat.Bmp);
                var bytes = ms.GetBuffer();
                ms.Close();
                return File(bytes, "image/png");
            }
        }
    }
}

FileExercise/Controllers/PurlController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;

namespace FileExercise.Controllers
{
    public class PurlController:ControllerBase
    {
        private readonly IWebHostEnvironment _environment;
        private readonly string _dir;

        public PurlController(IWebHostEnvironment environment)
        {
            _environment = environment;
            _dir = _environment.WebRootPath + "/file";
        }

        public IActionResult Upload(IFormFile file)
        {
            if (file == null)
            {
                return Ok("file = null");
            }

            var pathname = Path.Combine(_dir, file.FileName);

            using (var fileStream =
                new FileStream(pathname, FileMode.Create, FileAccess.Write))
            {
                file.CopyTo(fileStream);
            }
            return Ok("success");
        }

        /* Download 
         * 
         * 文件下载有2种方式
         * File是将文件读取到内存中(是Stream还是Byte还是String都无所谓)，再返回
         * PhysicalFile是直接返回硬盘中的文件
         * 
         * 其实还有第三种方式
         * 由于我们用了app.UseStaticFiles();
         * 所以我们可以访问静态文件
         */

        public IActionResult Display(string filename)
        {
            var pathname = Path.Combine(_dir, filename);
            var result = System.IO.File.ReadAllText(pathname);
            return Ok(result);
        }

        public IActionResult DisplayV2(string filename)
        {
            var pathname = Path.Combine(_dir, filename);
            var result = System.IO.File.OpenRead(pathname);

            return File(result, "image/png");
        }

        public IActionResult DisplayV3(string filename)
        {
            var pathname = Path.Combine(_dir, filename);
            var result = System.IO.File.OpenRead(pathname);
            return File(result, "image/png", "pic1.png");
        }

        public IActionResult DisplayV4(string filename)
        {
            var pathname = Path.Combine(_dir, filename);
            return PhysicalFile(pathname, "image/png", "pic1.png");
        }

    }
}

FileExercise/Controllers/UploadController.cs
using FileExercise.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using System.Collections.Generic;
using System.IO;

namespace FileExercise.Controllers
{
    public class UploadController : Controller
    {
        private readonly IHostEnvironment _env;

        private readonly string _dir;

        public UploadController(IHostEnvironment env)
        {
            _env = env;
            _dir = _env.ContentRootPath;
        }
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 上传单个文件
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult SingleFile(IFormFile file)
        {
            if(file == null)
            {
                return Ok("file = null");
            }

            var pathname = Path.Combine(_dir, file.FileName);

            using (var fileStream =
                new FileStream(pathname, FileMode.Create, FileAccess.Write))
            {
                file.CopyTo(fileStream);
            }
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// 同时上传多个文件
        /// </summary>
        /// <param name="files"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult MultipleFiles(IEnumerable<IFormFile> files)
        {
            foreach (var file in files)
            {
                var pathname = Path.Combine(_dir, file.FileName);

                using var fileStream =
                    new FileStream(pathname, FileMode.Create, FileAccess.Write);
                file.CopyTo(fileStream);
            }
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// 用自定义Model 上传文件
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public IActionResult FileInModel(CustomFileViewModel vm)
        {
            var pathname = Path.Combine(_dir, vm.Other);

            using (var fileStream =
                new FileStream(pathname, FileMode.Create, FileAccess.Write))
            {
                vm.File.CopyTo(fileStream);
            }
            //return RedirectToAction(nameof(Index));
            return Ok();
        }




    }
}

FileExercise/Views/Display/Index.cshtml
<h2>请选择图片</h2>
<form>
    

</form>

FileExercise/Views/Upload/Index.cshtml
<h1>home index</h1>

<!-- 通过form上传单个文件 -->
<h3>Single File</h3>
<form method="post" asp-action="SingleFile" asp-controller="Upload"
      enctype="multipart/form-data">
    <input type="file" name="file"/>
    <button type="submit">提交</button>
</form>

<!-- 通过form上传多个文件 -->
<h3>Multiple File</h3>
<form method="post" asp-action="multipleFiles"
      enctype="multipart/form-data">
    <input type="file" multiple name="files" />
    <button type="submit">提交</button>
</form>

<!-- 通过form上传单个文件，同时自定义文件名 -->
<h3>File In Model</h3>
<form method="post" asp-action="fileInModel"
      enctype="multipart/form-data">
    <input type="text" name="vm.Name" />
    <input type="file" name="vm.File" />
    <button type="submit">提交</button>
</form>

<!-- 通过JS上传单个文件 -->
<div>
    <h3>Single File Upload (JS)</h3>
    <input type="file" onchange="UploadFile(event)" />
</div>

<!-- 通过JS上传多个文件 -->
<div>
    <h3>Multiple Files Upload (JS)</h3>
    <input type="file" multiple onchange="UploadFiles(event)" />
</div>

<!-- 通过JS上传单个文件 同时修改文件名-->
<div>
    <h3>Single File Upload (JS)</h3>
    <input id="fileName" type="text" />
    <input type="file" onchange="UploadFileName(event)" />
</div>


<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
    console.log("aaa");

    //单个文件上传表单操作
    function UploadFile(event) {
        var file = event.target.files[0];
        var form = new FormData();
        form.append("file", file);
        axios.post("/Upload/SingleFile", form);
    }

    //多个文件上传表单操作
    function UploadFiles(event) {
        var files = event.target.files;
        var form = new FormData();
        for (var file of files) {
            form.append("files", file);
        }
        axios.post("/Upload/MultipleFiles", form);
    }

    //单个文件上传表单操作 同时修改名字
    function UploadFileName(event) {
        var fileName = document.getElementById("fileName").value;

        var file = event.target.files[0];
        var form = new FormData();
        form.append("vm.Name", fileName);
        form.append("vm.File", file);
        axios.post("/Upload/FileInModel", form);
    }


</script>